CREATE TABLE IF NOT EXISTS `wp_shop_address` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`province`  varchar(155) NOT NULL  COMMENT '省',
`phone`  varchar(100) NOT NULL  COMMENT '电话',
`name`  varchar(155) NOT NULL  COMMENT '收货人姓名',
`city`  varchar(155) NOT NULL  COMMENT '市',
`area`  varchar(155) NOT NULL  COMMENT '区',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`openid`  varchar(155) NOT NULL  COMMENT 'openid',
`address`  varchar(255) NOT NULL  COMMENT '详细地址',
`is_default`  char(10) NOT NULL  DEFAULT 2 COMMENT '默认地址',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_address','收货地址','0','','1','','1:基础','','','','','','10','','','1423406679','1423406679','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('province','省','varchar(155) NOT NULL','string','','','1','','0','0','1','1423412851','1423407402','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','电话','varchar(100) NOT NULL','string','','','1','','0','0','1','1423842267','1423407370','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','收货人姓名','varchar(155) NOT NULL','string','','','1','','0','0','1','1423406723','1423406723','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('city','市','varchar(155) NOT NULL','string','','','1','','0','0','1','1423407419','1423407419','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('area','区','varchar(155) NOT NULL','string','','','1','','0','0','1','1423407437','1423407437','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','1','','0','0','1','1423407462','1423407462','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','openid','varchar(155) NOT NULL','string','','','1','','0','0','1','1423407483','1423407483','','3','','regex','get_openid','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('address','详细地址','varchar(255) NOT NULL','string','','','1','','0','0','1','1423407502','1423407502','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_default','默认地址','char(10) NOT NULL','radio','2','','1','1:是\r\n2:否','0','0','1','1423408675','1423408675','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_banner` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(155) NOT NULL  COMMENT '标题',
`image`  int(10) UNSIGNED NOT NULL  COMMENT '图片',
`url`  varchar(255) NOT NULL  COMMENT '链接地址',
`is_show`  char(10) NOT NULL  DEFAULT 1 COMMENT '是否显示',
`sort`  int(10) UNSIGNED NOT NULL  DEFAULT 0 COMMENT '排序',
`token`  varchar(255) NOT NULL  COMMENT 'token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_banner','商铺首页幻灯片','0','','1','{"1":["title","image","url","is_show","sort"]}','1:基础','','','','','title:标题\r\nimage|get_img_html:图片\r\nurl:链接地址\r\nis_show|get_name_by_status:显示\r\nsort:排序\r\nid:操作:[EDIT]&module_id=[pid]|编辑,[DELETE]|删除','10','','','1423149677','1423153619','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','标题','varchar(155) NOT NULL','string','','可为空','1','','0','0','1','1426747361','1423149718','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('image','图片','int(10) UNSIGNED NOT NULL','picture','','建议宽高尺寸为600X300像素或以上','1','','0','1','1','1423149799','1423149788','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('url','链接地址','varchar(255) NOT NULL','string','','','1','','0','0','1','1426747399','1423149829','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_show','是否显示','char(10) NOT NULL','radio','1','','1','1:显示\r\n2:隐藏','0','0','1','1423149890','1423149890','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sort','排序','int(10) UNSIGNED NOT NULL','num','0','值越小越靠前','1','','0','0','1','1426747414','1423149920','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','0','','0','0','1','1423154585','1423154585','','3','','regex','get_token','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_categories` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`pid`  int(10) UNSIGNED NOT NULL  COMMENT '上级分类',
`name`  varchar(100) NOT NULL  COMMENT '分类名称',
`icon`  int(10) UNSIGNED NOT NULL  COMMENT '分类图标',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`is_show`  char(10) NOT NULL  DEFAULT 1 COMMENT '是否显示',
`sort`  int(10) UNSIGNED NOT NULL  DEFAULT 0 COMMENT '排序',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_categories','商品分类','0','','1','{"1":["name","icon","sort","is_show","pid"]}','1:基础','','','','','id:ID\r\nname:分类名称\r\nicon|get_img_html:分类图标\r\nsort:排序\r\nis_show|get_name_by_status:是否隐藏\r\nid:10%操作:[EDIT]|编辑,[DELETE]|删除','10','name','','1421653523','1426234997','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pid','上级分类','int(10) UNSIGNED NOT NULL','select','','如果是一级分类，选择“无”即可','1','','0','1','1','1426747734','1421654076','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','分类名称','varchar(100) NOT NULL','string','','分类名称','1','','0','1','1','1421654051','1421654051','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('icon','分类图标','int(10) UNSIGNED NOT NULL','picture','','需要显示时上传','1','','0','0','1','1426747655','1421654105','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','0','','0','0','1','1421661559','1421658870','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_show','是否显示','char(10) NOT NULL','radio','1','','1','1:显示\r\n0:隐藏','0','1','1','1421654169','1421654169','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sort','排序','int(10) UNSIGNED NOT NULL','num','0','值越小越靠前','1','','0','0','1','1426747673','1421655793','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;


CREATE TABLE IF NOT EXISTS `wp_shop_footer` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`url`  varchar(255) NULL   COMMENT '关联URL',
`title`  varchar(50) NOT NULL  COMMENT '菜单名',
`pid`  tinyint(2) NULL  DEFAULT 0 COMMENT '上级菜单',
`sort`  tinyint(4) NULL   DEFAULT 0 COMMENT '排序号',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`icon`  int(10) unsigned NULL   COMMENT '图标',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_footer','底部导航','0','','1','{"1":["pid","title","url","sort"]}','1:基础','','','','','title:菜单名\r\nicon:图标\r\nurl:关联URL\r\nsort:排序号\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','title','','1394518309','1396507698','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('url','关联URL','varchar(255) NULL ','string','','可用{site_url}代表当前网站根地址','1','','0','0','1','1399083504','1394519090','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','菜单名','varchar(50) NOT NULL','string','','可创建最多 3 个一级菜单，每个一级菜单下可创建最多 5 个二级菜单。编辑中的菜单不会马上被用户看到，请放心调试。','1','','0','0','1','1394519941','1394518988','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pid','上级菜单','tinyint(2) NULL','select','0','如果是一级菜单，选择“无”即可','1','0:无','0','0','1','1426748036','1394518930','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sort','排序号','tinyint(4) NULL ','num','0','数值越小越靠前','1','','0','0','1','1394523288','1394519175','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1394526820','1394526820','','3','','regex','get_token','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('icon','图标','int(10) unsigned NULL ','picture','','根据选择的底部模板决定是否需要上传图标','1','','0','0','1','1396506297','1396506297','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_orders` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`name`  varchar(155) NOT NULL  COMMENT '收货人姓名',
`y_price`  DOUBLE(12,2) UNSIGNED NOT NULL  COMMENT '运费',
`province`  varchar(155) NOT NULL  COMMENT '省',
`payStatus`  char(10) NOT NULL  DEFAULT 1 COMMENT '支付状态',
`payTime`  int(10)  null  COMMENT '支付时间',
`cTime`  int(10) NOT NULL  COMMENT '创建时间',
`ordernum`  varchar(255) NOT NULL  COMMENT '订单单号',
`total_price`  DOUBLE(12,2) UNSIGNED NOT NULL  COMMENT '实际总价格',
`p_price`  DOUBLE(12,2) UNSIGNED NOT NULL  COMMENT '商品总价格',
`remarks`  varchar(255) NOT NULL  COMMENT '备注',
`address`  varchar(255) NOT NULL  COMMENT '详细地址',
`area`  varchar(155) NOT NULL  COMMENT '区',
`city`  varchar(155) NOT NULL  COMMENT '市',
`orderStatus`  char(10) NOT NULL  DEFAULT 1 COMMENT '订单类型',
`wuliuStatus`  char(10) NOT NULL  DEFAULT 1 COMMENT '物流状态',
`wuliu_gongsi`  char(10) NOT NULL  COMMENT '物流公司',
`wuliu_num`  varchar(255) NOT NULL  COMMENT '物流单号',
`phone`  varchar(155) NOT NULL  COMMENT '收货人电话',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`openid`  varchar(255) NOT NULL  COMMENT 'openid',
`payType`  char(10) NOT NULL  DEFAULT 1 COMMENT '支付类型',
`transaction_id`  varchar(255) NOT NULL  COMMENT '微信支付单号',
`close_remark`  text NOT NULL  COMMENT '关闭原因',
`r_price`  int(10) UNSIGNED NOT NULL  DEFAULT 0 COMMENT '折扣优惠',
`close_mid`  varchar(255) NOT NULL  COMMENT '关闭管理员',
`close_from`  char(50) NOT NULL  COMMENT '关闭来源',
`close_time`  int(10) NOT NULL  COMMENT '关闭时间',
`dept_from`  int(10) UNSIGNED  COMMENT '来源部门',
`dept_pai`  int(10) UNSIGNED NOT NULL  COMMENT '订单派送店铺',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_orders','商品订单','0','','1','{"1":["ordernum","cTime","payTime","wuliuStatus","payStatus","orderStatus","province","city","area","address","remarks","p_price","total_price","y_price","name","phone","token","openid","payType","transaction_id","wuliu_num","wuliu_gongsi","close_remark","r_price","close_mid","close_from","close_time","dept_id"]}','1:基础','','','','','id:ID\r\nordernum:订单号\r\nname:收货人\r\nphone:电话\r\ntotal_price:订单总价(元)\r\ndept_from|get_dept_name:来源店铺\r\npayStatus|get_name_by_status:支付状态\r\npayType|get_name_by_status:支付类型\r\ncTime|time_format:创建日期\r\nid:操作:<a href="#" class="idinfo" val="[id]">详情</a>','10','ordernum|name|phone','','1423563861','1430366237','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','收货人姓名','varchar(155) NOT NULL','string','','','1','','0','0','1','1423641005','1423641005','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('y_price','运费','DOUBLE(12,2) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423645799','1423640928','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('province','省','varchar(155) NOT NULL','string','','','1','','0','0','1','1423640611','1423640611','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('payStatus','支付状态','char(10) NOT NULL','radio','1','','1','1:未支付\r\n2:已支付','0','0','1','1423647945','1423564488','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('payTime','支付时间','int(10)  null','datetime','','','1','','0','0','1','1423647207','1423564018','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','创建时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1423647142','1423563990','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ordernum','订单单号','varchar(255) NOT NULL','string','','','1','','0','0','1','1423563954','1423563954','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('total_price','实际总价格','DOUBLE(12,2) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423645862','1423640812','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('p_price','商品总价格','DOUBLE(12,2) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423645784','1423640769','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('remarks','备注','varchar(255) NOT NULL','string','','','1','','0','0','1','1423640732','1423640732','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('address','详细地址','varchar(255) NOT NULL','string','','','1','','0','0','1','1423640662','1423640662','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('area','区','varchar(155) NOT NULL','string','','','1','','0','0','1','1423640647','1423640647','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('city','市','varchar(155) NOT NULL','string','','','1','','0','0','1','1423640630','1423640630','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('orderStatus','订单类型','char(10) NOT NULL','radio','1','','1','1:正常订单\r\n2:取消订单','0','0','1','1423647959','1423564547','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wuliuStatus','物流状态','char(10) NOT NULL','radio','1','','1','1:待发货\r\n2:待收货\r\n3:已收货','0','0','1','1423647922','1423564443','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wuliu_gongsi','物流公司','char(10) NOT NULL','string','','','1','','0','0','1','1423756585','1423756577','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wuliu_num','物流单号','varchar(255) NOT NULL','string','','','1','','0','0','1','1423756599','1423756599','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','收货人电话','varchar(155) NOT NULL','string','','','1','','0','0','1','1423641027','1423641027','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','1','','0','0','1','1423641635','1423641624','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','openid','varchar(255) NOT NULL','string','','','1','','0','0','1','1423641660','1423641660','','3','','regex','get_openid','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('payType','支付类型','char(10) NOT NULL','radio','1','','1','1:微信支付\r\n2:支付宝支付\r\n3:货到付款\r\n4:余额支付','0','0','1','1429528210','1423647992','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('transaction_id','微信支付单号','varchar(255) NOT NULL','string','','','1','','0','0','1','1423724939','1423724939','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('close_remark','关闭原因','text NOT NULL','textarea','','','1','','0','0','1','1425628359','1425628359','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('r_price','折扣优惠','int(10) UNSIGNED NOT NULL','num','0','','1','','0','0','1','1427447750','1427447750','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('close_mid','关闭管理员','varchar(255) NOT NULL','string','','','1','','0','0','1','1427769662','1427769662','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('close_from','关闭来源','char(50) NOT NULL','select','','','1','1:客户\r\n2:管理员','0','0','1','1427773543','1427769714','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('close_time','关闭时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1427782896','1427782896','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dept_from','来源部门','int(10) UNSIGNED','num','','','0','','0','0','1','1430103534','1430103534','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('dept_pai','订单派送店铺','int(10) UNSIGNED NOT NULL','num','','','1','','0','0','1','1430386410','1430306271','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_order_detail` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`order_id`  int(10) UNSIGNED NOT NULL  COMMENT '所属订单',
`head_img`  int(10) UNSIGNED NOT NULL  COMMENT '商品图片',
`name`  varchar(255) NOT NULL  COMMENT '商品名称',
`true_price`  DOUBLE(12,2) UNSIGNED NOT NULL  COMMENT '实际价格',
`num`  int(10) UNSIGNED NOT NULL  COMMENT '数量',
`number`  varchar(255) NOT NULL  COMMENT '商品编号',
`old_price`  double(12,2) UNSIGNED NOT NULL  COMMENT '原价',
`p_id`  int(10) UNSIGNED NOT NULL  COMMENT '商品id',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_order_detail','订单商品详情','0','','1','','1:基础','','','','','','10','','','1423641356','1423641356','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('order_id','所属订单','int(10) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423641391','1423641391','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('head_img','商品图片','int(10) UNSIGNED NOT NULL','picture','','','1','','0','0','1','1423648812','1423641445','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','商品名称','varchar(255) NOT NULL','string','','','1','','0','0','1','1423641468','1423641468','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('true_price','实际价格','DOUBLE(12,2) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423648763','1423641507','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('num','数量','int(10) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423641532','1423641532','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('number','商品编号','varchar(255) NOT NULL','string','','','1','','0','0','1','1426238123','1423648700','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('old_price','原价','double(12,2) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423648738','1423648738','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('p_id','商品id','int(10) UNSIGNED NOT NULL','num','','','1','','0','0','1','1423649574','1423649574','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_products` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`view_num`  int(10) UNSIGNED NOT NULL  DEFAULT 0 COMMENT '查看次数',
`keyword`  varchar(100) NOT NULL  COMMENT '关键词',
`keyword_type`  char(50) NOT NULL  COMMENT '关键词类型',
`cover`  int(10) UNSIGNED NOT NULL  COMMENT '封面图片',
`sellnum`  int(10) UNSIGNED NOT NULL  DEFAULT 0 COMMENT '销量',
`cTime`  int(10) UNSIGNED NOT NULL  COMMENT '创建时间',
`cate_id`  char(50) NOT NULL  COMMENT '所属分类',
`token`  varchar(100) NOT NULL  COMMENT 'token',
`intro`  text NOT NULL  COMMENT '基础信息',
`is_show`  char(10) NOT NULL  DEFAULT 1 COMMENT '是否上架',
`unit`  varchar(50) NOT NULL  COMMENT '单位',
`meas`  varchar(50) NOT NULL  COMMENT '规格',
`old_price`  DOUBLE(12,2)  UNSIGNED NOT NULL  COMMENT '原价',
`true_price`  DOUBLE(12,2) UNSIGNED NOT NULL  COMMENT '现价',
`head_img`  int(10) UNSIGNED NOT NULL  COMMENT '商品图片',
`name`  varchar(255) NOT NULL  COMMENT '商品名称',
`number`  varchar(155) NOT NULL  COMMENT '商品编号',
`content`  text NOT NULL  COMMENT '商品详情',
`is_rate`  char(10) NOT NULL  DEFAULT 1 COMMENT '允许折扣',
`desc`  varchar(255) NOT NULL  COMMENT '商品简介',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_products','商品信息','0','','1','{"1":["cover","keyword","keyword_type","name","cate_id","number","head_img","desc","old_price","true_price","intro","content","is_show","sellnum","view_num","is_rate"]}','1:基础','','','','','id:ID\r\nhead_img|get_img_html:图片\r\nnumber:商品编码\r\nname:商品名称\r\ncate_id|get_cate_by_id:所属分类\r\nold_price:原价(元)\r\ntrue_price:现价(元)\r\nsellnum:销量\r\nview_num:查阅\r\nid:12%操作:[EDIT]|编辑,[DELETE]|删除','10','name|number','','1421735634','1428998061','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('view_num','查看次数','int(10) UNSIGNED NOT NULL','num','0','','1','','0','0','1','1428996708','1428996708','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('keyword','关键词','varchar(100) NOT NULL','string','','','1','','0','0','1','1422001573','1422001573','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('keyword_type','关键词类型','char(50) NOT NULL','select','','','1','0:完全匹配\r\n1:左边匹配\r\n2:右边匹配\r\n3:模糊匹配','0','0','1','1422001505','1422001505','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cover','封面图片','int(10) UNSIGNED NOT NULL','picture','','建议宽高尺寸为600X300像素或以上','1','','0','0','1','1426748666','1422001315','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sellnum','销量','int(10) UNSIGNED NOT NULL','num','0','','1','','0','0','1','1421837758','1421837758','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','创建时间','int(10) UNSIGNED NOT NULL','num','','','0','','0','0','1','1421837310','1421837283','','3','','regex','time','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cate_id','所属分类','char(50) NOT NULL','select','','','1','get_shop_categories','0','1','1','1421997473','1421826333','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(100) NOT NULL','string','','','0','','0','0','1','1421739983','1421738475','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('intro','基础信息','text NOT NULL','textarea','','可注明产地、规格、重量等商品基本信息','1','','0','0','1','1426749442','1421925191','','3','','regex','nl2br','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_show','是否上架','char(10) NOT NULL','radio','1','','1','1:上架\r\n2:下架','0','1','1','1421835916','1421835916','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('unit','单位','varchar(50) NOT NULL','string','','','0','','0','0','1','1423570555','1421735998','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('meas','规格','varchar(50) NOT NULL','string','','','0','','0','0','1','1423570543','1421736024','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('old_price','原价','DOUBLE(12,2)  UNSIGNED NOT NULL','num','','支持小数点后两位，单位：元','1','','0','1','1','1426749371','1421736055','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('true_price','现价','DOUBLE(12,2) UNSIGNED NOT NULL','num','','支持小数点后两位，单位：元','1','','0','1','1','1426749380','1421736075','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('head_img','商品图片','int(10) UNSIGNED NOT NULL','picture','','建议宽高尺寸为600X600像素或以上','1','','0','1','1','1426749303','1421736100','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','商品名称','varchar(255) NOT NULL','string','','','1','','0','1','1','1421735714','1421735714','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('number','商品编号','varchar(155) NOT NULL','string','','','1','','0','1','1','1421735763','1421735763','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','商品详情','text NOT NULL','editor','','','1','','0','0','1','1421925155','1421736134','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_rate','允许折扣','char(10) NOT NULL','select','1','选择否，则此商品不享受会员折扣','1','1:是\r\n0:否','0','0','1','1427454629','1427453719','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('desc','商品简介','varchar(255) NOT NULL','textarea','','分享等场景时显示的简介文字','1','','0','0','1','1428683481','1428662490','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_topic` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(155) NOT NULL  COMMENT '专题名称',
`image`  int(10) UNSIGNED NOT NULL  COMMENT '封面图片',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`is_show`  char(10) NOT NULL  DEFAULT 1 COMMENT '是否显示',
`sort`  int(10) UNSIGNED NOT NULL  DEFAULT 0 COMMENT '排序',
`products_id`  varchar(255) NOT NULL  COMMENT '所含商品',
`head_image`  int(10) UNSIGNED NOT NULL  COMMENT '专题头图',
`color`  varchar(20) NOT NULL  DEFAULT 'dc214c' COMMENT '专题颜色',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_topic','商铺专题','0','','1','{"1":["title","image","head_image","is_show","sort","color"]}','1:基础','','','','','id:ID\r\ntitle:商品名称\r\nimage|get_img_html:图片\r\nis_show|get_name_by_status:是否显示\r\nsort:排序\r\nid:15%操作:[EDIT]|编辑,[DELETE]|删除,setproduct?id=[id]|所含商品','10','','','1423237371','1426219123','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','专题名称','varchar(155) NOT NULL','string','','','1','','0','1','1','1423237924','1423237405','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('image','封面图片','int(10) UNSIGNED NOT NULL','picture','','建议宽高尺寸为600X300像素或以上','1','','0','1','1','1426747463','1423237693','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','0','','0','0','1','1423238491','1423237777','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_show','是否显示','char(10) NOT NULL','radio','1','','1','1:显示\r\n2:隐藏','0','0','1','1423237845','1423237845','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sort','排序','int(10) UNSIGNED NOT NULL','num','0','值越小越靠前','1','','0','0','1','1426747547','1423237958','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('products_id','所含商品','varchar(255) NOT NULL','string','','','0','','0','0','1','1423398245','1423398245','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('head_image','专题头图','int(10) UNSIGNED NOT NULL','picture','','显示在专题页顶部，建议宽度尺寸为600像素以上，高度自适应','1','','0','0','1','1426747482','1423565949','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('color','专题颜色','varchar(20) NOT NULL','color','dc214c','专题页背景色，需要改变默认色时设置','1','','0','0','1','1426747584','1425884302','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

